version: "3.9"

services:
  api:
    container_name: measurements-api
    hostname: measurements-api.local
    build: ./src/measurements-api/
    depends_on:
      - db
    ports:
      - "7001:80"
    networks:
     app:
        ipv4_address: 172.24.0.2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # collector:
  #   container_name: ruuvi_data_collector
  #   hostname: collector.local
  #   build: ./src/measurements-collector/
  #   depends_on:
  #     - db
  #   networks:
  #     app:
  #       ipv4_address: 172.24.0.3

  db:
    container_name: cosmosdb
    hostname: cosmosdb.local
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator"
    tty: true
    restart: always
    mem_limit: 3G
    cpu_count: 4
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=172.24.0.99
    ports:
      - "8081:8081"
      - "10251-10254:10251-10254"
    networks:
      app:
        ipv4_address: 172.24.0.99
    volumes:
       - cosmosdb:/data/db

networks:
  app:
    ipam:
        driver: default
        config:
          - subnet: "172.24.0.0/16"

volumes:
  cosmosdb:
