//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.11.1.0 (NJsonSchema v10.4.3.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Text.Json;
using Microsoft.AspNetCore.Mvc;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"

namespace OpenApi.Measurements.Api
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.11.1.0 (NJsonSchema v10.4.3.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IMeasurementsController
    {
        /// <param name="startTime">Start time as defined by RFC 3339, section 5.6, for example, 2022-06-21T17:32:28Z</param>
        /// <param name="endTime">End time as defined by RFC 3339, section 5.6, for example, 2022-06-22T17:32:28Z</param>
        /// <param name="source">Measurement source identifier i.e. "C6:4C:96:B3:20:7E"</param>
        /// <param name="limit">Maximum number of results to return</param>
        /// <returns>Measurements response</returns>
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<MeasurementsDataResponse>>> MeasurementsGetAsync(System.DateTime startTime, System.DateTime endTime, string source, int limit, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> MeasurementsPostAsync(System.Collections.Generic.IEnumerable<Measurement> body, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.11.1.0 (NJsonSchema v10.4.3.0 (Newtonsoft.Json v12.0.0.0))")]
    [ApiController]
    public partial class MeasurementsController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IMeasurementsController _implementation;
    
        public MeasurementsController(IMeasurementsController implementation)
        {
            _implementation = implementation;
        }
    
        /// <param name="startTime">Start time as defined by RFC 3339, section 5.6, for example, 2022-06-21T17:32:28Z</param>
        /// <param name="endTime">End time as defined by RFC 3339, section 5.6, for example, 2022-06-22T17:32:28Z</param>
        /// <param name="source">Measurement source identifier i.e. "C6:4C:96:B3:20:7E"</param>
        /// <param name="limit">Maximum number of results to return</param>
        /// <returns>Measurements response</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("measurements", Name = "getMeasurements")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<MeasurementsDataResponse>>> MeasurementsGet([Microsoft.AspNetCore.Mvc.FromQuery] [Microsoft.AspNetCore.Mvc.ModelBinding.BindRequired] System.DateTime startTime, [Microsoft.AspNetCore.Mvc.FromQuery] [Microsoft.AspNetCore.Mvc.ModelBinding.BindRequired] System.DateTime endTime, [Microsoft.AspNetCore.Mvc.FromQuery] string source, [Microsoft.AspNetCore.Mvc.FromQuery] int? limit, System.Threading.CancellationToken cancellationToken)
        {
            return _implementation.MeasurementsGetAsync(startTime, endTime, source, limit ?? 1000, cancellationToken);
        }
    
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("measurements", Name = "createMeasurements")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> MeasurementsPost([Microsoft.AspNetCore.Mvc.FromBody] [Microsoft.AspNetCore.Mvc.ModelBinding.BindRequired] System.Collections.Generic.IEnumerable<Measurement> body, System.Threading.CancellationToken cancellationToken)
        {
            return _implementation.MeasurementsPostAsync(body, cancellationToken);
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.11.1.0 (NJsonSchema v10.4.3.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface ISensorsController
    {
        /// <returns>Sensors response</returns>
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<Sensor>>> SensorsGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
        /// <returns>Sensor response</returns>
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Sensor>> SensorsPostAsync(Sensor body, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
        /// <param name="id">Id of sensor to fecth</param>
        /// <returns>Sensor response</returns>
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Sensor>> SensorsGetAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
        /// <param name="id">Id of sensor to delete</param>
        /// <returns>Sensor deleted</returns>
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> SensorsDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.11.1.0 (NJsonSchema v10.4.3.0 (Newtonsoft.Json v12.0.0.0))")]
    [ApiController]
    public partial class SensorsController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private ISensorsController _implementation;
    
        public SensorsController(ISensorsController implementation)
        {
            _implementation = implementation;
        }
    
        /// <returns>Sensors response</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("sensors", Name = "getSensors")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<Sensor>>> SensorsGet(System.Threading.CancellationToken cancellationToken)
        {
            return _implementation.SensorsGetAsync(cancellationToken);
        }
    
        /// <returns>Sensor response</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("sensors", Name = "createSensor")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Sensor>> SensorsPost([Microsoft.AspNetCore.Mvc.FromBody] [Microsoft.AspNetCore.Mvc.ModelBinding.BindRequired] Sensor body, System.Threading.CancellationToken cancellationToken)
        {
            return _implementation.SensorsPostAsync(body, cancellationToken);
        }
    
        /// <param name="id">Id of sensor to fecth</param>
        /// <returns>Sensor response</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("sensors/{id}", Name = "getSensorById")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<Sensor>> SensorsGet([Microsoft.AspNetCore.Mvc.ModelBinding.BindRequired] string id, System.Threading.CancellationToken cancellationToken)
        {
            return _implementation.SensorsGetAsync(id, cancellationToken);
        }
    
        /// <param name="id">Id of sensor to delete</param>
        /// <returns>Sensor deleted</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("sensors/{id}", Name = "deleteSensor")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> SensorsDelete([Microsoft.AspNetCore.Mvc.ModelBinding.BindRequired] string id, System.Threading.CancellationToken cancellationToken)
        {
            return _implementation.SensorsDeleteAsync(id, cancellationToken);
        }
    
    }

    /// <summary>Measurement data from one source</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.4.3.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Measurement 
    {
        /// <summary>Measurement time as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z</summary>
        [System.Text.Json.Serialization.JsonPropertyName("time")]
        public System.DateTime Time { get; set; }
    
        /// <summary>Source of measurement. With ruuvi tag this is MAC.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("source")]
        public string Source { get; set; }
    
        /// <summary>Temperature in celsius.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("temperature")]
        public double Temperature { get; set; }
    
        /// <summary>Pressure</summary>
        [System.Text.Json.Serialization.JsonPropertyName("pressure")]
        public double Pressure { get; set; }
    
        /// <summary>Humidity</summary>
        [System.Text.Json.Serialization.JsonPropertyName("humidity")]
        public double Humidity { get; set; }
    
        /// <summary>Battery level. TBD what is the format.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("battery")]
        public double Battery { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("acceleration")]
        public Acceleration Acceleration { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>Acceleration</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.4.3.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Acceleration 
    {
        [System.Text.Json.Serialization.JsonPropertyName("acceleration")]
        public double Acceleration1 { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("accelerationX")]
        public double AccelerationX { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("accelerationY")]
        public double AccelerationY { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("accelerationZ")]
        public double AccelerationZ { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>Sensor producing measurements data</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.4.3.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Sensor 
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>Response object for measurements.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.4.3.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class MeasurementsDataResponse 
    {
        [System.Text.Json.Serialization.JsonPropertyName("count")]
        public int Count { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("items")]
        public System.Collections.Generic.List<Measurement> Items { get; set; }
    
    
    }
    
    /// <summary>Problem details based on rfc7807.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.4.3.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class ProblemDetails 
    {
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string Type { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("title")]
        public string Title { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public int? Status { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("detail")]
        public string Detail { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("instance")]
        public string Instance { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("extensions")]
        public System.Collections.Generic.IDictionary<string, object> Extensions { get; set; }
    
    
    }
    
    /// <summary>Problem details for validation errors.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.4.3.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class ValidationProblemDetails 
    {
        [System.Text.Json.Serialization.JsonPropertyName("errors")]
        public System.Collections.Generic.IDictionary<string, System.Collections.Generic.List<string>> Errors { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string Type { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("title")]
        public string Title { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public int? Status { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("detail")]
        public string Detail { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("instance")]
        public string Instance { get; set; }
    
        [System.Text.Json.Serialization.JsonPropertyName("extensions")]
        public System.Collections.Generic.IDictionary<string, object> Extensions { get; set; }
    
    
    }

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108