# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import measurements_api_client
from measurements_api_client.paths.sensors_id import put  # noqa: E501
from measurements_api_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestSensorsId(ApiTestMixin, unittest.TestCase):
    """
    SensorsId unit test stubs
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = put.ApiForput(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''




if __name__ == '__main__':
    unittest.main()
