# coding: utf-8

"""
    Measurements API

    API to fetch ruuvi tag measurements data.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: tbd@example.com
    Generated by: https://openapi-generator.tech
"""

from measurements_api_client.paths.measurements.get import GetMeasurements
from measurements_api_client.paths.measurements_batch_insert.post import PostMeasurements


class MeasurementsApi(
    GetMeasurements,
    PostMeasurements,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
