# coding: utf-8

"""
    Measurements API

    API to fetch ruuvi tag measurements data.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: tbd@example.com
    Generated by: https://openapi-generator.tech
"""

from measurements_api_client.paths.sensors_id.delete import DeleteSensor
from measurements_api_client.paths.sensors_id.get import GetSensorById
from measurements_api_client.paths.sensors.get import GetSensors
from measurements_api_client.paths.sensors.post import PostSensor
from measurements_api_client.paths.sensors_id.put import PutSensor


class SensorsApi(
    DeleteSensor,
    GetSensorById,
    GetSensors,
    PostSensor,
    PutSensor,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
