# coding: utf-8

"""
    Measurements API

    API to fetch ruuvi tag measurements data.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: tbd@example.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import measurements_api_client
from measurements_api_client.model.measurements_data_response import MeasurementsDataResponse
from measurements_api_client import configuration


class TestMeasurementsDataResponse(unittest.TestCase):
    """MeasurementsDataResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
