# coding: utf-8

"""
    Measurements API

    API to fetch ruuvi tag measurements data.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: tbd@example.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import measurements_api_client
from measurements_api_client.model.validation_problem_details import ValidationProblemDetails
from measurements_api_client import configuration


class TestValidationProblemDetails(unittest.TestCase):
    """ValidationProblemDetails unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
